apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: simple-pod
  name: simple-service
spec:
  ports:
  - port: 3555
    protocol: TCP
    targetPort: 3555
  selector:
    run: simple-pod
status:
  loadBalancer: {}
