apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-pod
  name: simple-pod
spec:
  ports:
  - name: 25-25
    port: 25
    protocol: TCP
    targetPort: 25
  selector:
    app: simple-pod
  type: ClusterIP
status:
  loadBalancer: {}
