apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    tier: frontend
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    NodePort: 30080
  selector:
    app: nginx
    tier: frontend
  type: NodePort
status:
  loadBalancer: {}
