apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: super-user-pod
  name: super-user-pod
spec:
  containers:
  - image: busybox:1.28
    name: super-user-pod
    command:
      - "sleep"
      - "4800"
    securityContext:  
      capabilities:
        add: ["SYS_TIME"]